stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  image: node:13
  script:
    - npm install
    - ./node_modules/.bin/ng build

  artifacts:
    paths:
      - ./dist/DSC
