stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  image: node:13
  script:
    - npm install
    - ./node_modules/.bin/ng build --prod
    - tar cJf dsc-frontend.tar.xz -C dist/DSC/ .
  artifacts:
    paths:
      - ./dsc-frontend.tar.xz
