stages:
  - build
  - package

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  image: node:13
  script:
    - npm install
    - ./node_modules/.bin/ng build

package:
  stage: package
  script:
    - tar cJf dsc.tar.xz -C dist/DSC/ .
  artifacts:
    paths:
      - ./dsc.tar.xz
