stages:
  - build

build:
  stage: build
  image: node:13
  script:
    - npm install
    - git submodule init
    - git submodule update
    - ./node_modules/.bin/ng build

  artifacts:
    paths:
      - ./dist/DSC
